### PR TITLE
Austin users recovered

### PR DESCRIPTION
**Pull request by austinvoong**
Worked on linking the backend. Got a good start, added functions so that it is possible for a user account to be created during signup. Currently will console log this, I'll be able to build off of this and finish the backend. Also, updated httpUltilities so we can run on local for now. 

image

### CODE REVIEW

**Comment by SameerNadeem** [comment]
Hey Austin, this looks great. A potential improvement could involve consolidating repeated logic, like default stats initialization

**Comment by TreyMartin0** [comment]
Code looks good to me. Thanks for returning it back to local until we can fix the issue with the backend and deploying to azure. Then we should be able to pass all the test

**Review by DuyNguyen6080 — COMMENTED** [review]
The code look good to me. Nice work

**Comment by arian-housh** [comment]
Good job. Like Trey and Sameer said being able to run locally is a big help now while we fix our program. The deploy fails because of unused variables. This is a very easy fix because you can just delete them. That is if we not need them obviously...

**Pull request merged**
