### PR TITLE
Feature/react router navigation

### PR DESCRIPTION
**Pull request by arian-housh**
Implemented React Router:

Affected files:

app.jsx
Navigation.jsx
Welcome.jsx
Calender.jsx

### CODE REVIEW

**Comment by TreyMartin0** [comment]
Check failed due to react-router-dom not being installed -- easy fix. We just need to run npm install react-router-dom then it'll pass. CI failed do to not running npx prettier --write . before pushing. Besides that code looks good and router is functional!

**Comment by DuyNguyen6080** [comment]
i think the workflows fail because .gitingnore ignore nodemodules file. so npm install in the web static workflow is not enough. I suggest add npm install <packages> for example npm install react react-dom or npm install express. hope this make the workflow pass

**Comment by SameerNadeem** [comment]
to address the issue with the workflow failure, another approach could be to explicitly cache the node_modules directory in the CI pipeline. This way, dependencies won't need to be re-installed from scratch each time, reducing the chance of errors caused by missing modules.

**Comment by austinvoong** [comment]
I agree with Sameer, I think that the node_modules is causing problems. I keep having to add it to my .gitignore or else my code takes forever to run. The React router LGTM

**Pull request merged**
